POST http://localhost:8080/customers
Content-Type: application/json

{
  "name": "world"
}

###

GET http://localhost:8080/users/Pallat

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "world"
}

